/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AlbumsIndexImport } from './routes/albums.index'
import { Route as AlbumsAlbumIdImport } from './routes/albums.$albumId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsIndexRoute = AlbumsIndexImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsAlbumIdRoute = AlbumsAlbumIdImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdImport
      parentRoute: typeof rootRoute
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/albums': typeof AlbumsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/albums': typeof AlbumsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/albums/': typeof AlbumsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/albums/$albumId' | '/albums'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/albums/$albumId' | '/albums'
  id: '__root__' | '/' | '/albums/$albumId' | '/albums/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/albums/$albumId",
        "/albums/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/albums/$albumId": {
      "filePath": "albums.$albumId.tsx"
    },
    "/albums/": {
      "filePath": "albums.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
